### ISSUE TITLE
Better line wrapping

### ISSUE THREAD

**Issue by Nhqml** [prologin/iorgen#28]
The current behavior for line wrapping ignores any existing line break (because `textwrap.wrap()` does). Maybe it would be better to split lines before wrapping them and flatten the result?

You can check the "wrong wrapping" with:

```yaml
output: >
  This is a message with multiple lines:
  - line 1
  - line 2
```

Which will result in a single line:

```md
This is a message with multiple lines: - line 1 - line 2
```
