### ISSUE TITLE
Support constraints with future-declared variable

### ISSUE THREAD

**Issue by Shaac** [prologin/iorgen#33]
The following input fails.

```yaml
input:
  - type: int
    name: N
    min: K
  - type: int
    name: K
```

If you ask me, this should probably not be supported, but some people are using it, so I guess iorgen should support it.
